spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/pdfscanner_db
spring.datasource.username=zhappar_a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

secret.key=8Cr6eIxMt8xVSJ7Ffi5uIEidC0cWUaiDlARbKKSNp4S

bucket4j.enabled=false